//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteYonetim.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GelirGider
    {
        public int ID { get; set; }
        public string GelirGiderTuru { get; set; }
        public Nullable<decimal> GelirGiderTutar { get; set; }
        public string GelirGiderAciklama { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string KaydedenKisi { get; set; }
    }
}
