//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteYonetim.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbSYSEntities2 : DbContext
    {
        public DbSYSEntities2()
            : base("name=DbSYSEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<GelirGider>().ToTable("GelirGider");
            modelBuilder.Entity<SiteAidat>().ToTable("SiteAidat");
            modelBuilder.Entity<SiteSakinleri>().ToTable("SiteSakinleri");
            modelBuilder.Entity<Yonetici>().ToTable("Yonetici");
        }
        public virtual DbSet<GelirGider> GelirGider { get; set; }
        public virtual DbSet<SiteAidat> SiteAidat { get; set; }
        public virtual DbSet<SiteSakinleri> SiteSakinleri { get; set; }
        public virtual DbSet<Yonetici> Yonetici { get; set; }

    }
}
